
#include "gridshooter.buildv1.1.15/windows_release_mx/include/gridshooter_stdlib_collections_2container.h"

t_stdlib_collections_IContainer_1Tt_default_Bullet_2::~t_stdlib_collections_IContainer_1Tt_default_Bullet_2(){
}

t_stdlib_collections_IIterator_1Tt_default_Bullet_2::~t_stdlib_collections_IIterator_1Tt_default_Bullet_2(){
}

t_stdlib_collections_IContainer_1Tt_default_Actor_2::~t_stdlib_collections_IContainer_1Tt_default_Actor_2(){
}

t_stdlib_collections_IIterator_1Tt_default_Actor_2::~t_stdlib_collections_IIterator_1Tt_default_Actor_2(){
}

void mx2_gridshooter_stdlib_collections_2container_init_f(){
}
